name: flutter_telephony_info
description: A plugin to retrieve information from the android telephony library.
version: 0.0.1
homepage: https://github.com/grfc-ru/flutter_telephony_info
repository: https://github.com/grfc-ru/flutter_telephony_info/tree/main
issue_tracker: https://github.com/grfc-ru/flutter_telephony_info/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.7.0'

platforms:
  android:

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  pigeon: ^9.1.1

flutter:
  plugin:
    platforms:
      android:
        package: ru.grfc.telephony.flutter_telephony_info
        pluginClass: FlutterTelephonyInfoPlugin
