// Autogenerated from Pigeon (v10.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package ru.grfc.telephony.flutter_telephony_info

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class TelephonyInfo (
  /** The name of the user’s home cellular service provider. */
  val displayName: String? = null,
  /** The mobile network code (MNC) for the user’s cellular service provider. */
  val mobileNetworkCode: String? = null,
  /** The mobile network generation: LTE, HSDPA, e.t.c */
  val radioType: String? = null,
  /** The mobile network radioType: 5G, 4G ... 2G */
  val networkGeneration: String? = null,
  /** The cell id (cid) and local area code */
  val cellId: String? = null,
  /** The cell signal strenght */
  val cellSignalStrength: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): TelephonyInfo {
      val displayName = list[0] as String?
      val mobileNetworkCode = list[1] as String?
      val radioType = list[2] as String?
      val networkGeneration = list[3] as String?
      val cellId = list[4] as String?
      val cellSignalStrength = list[5] as String?
      return TelephonyInfo(displayName, mobileNetworkCode, radioType, networkGeneration, cellId, cellSignalStrength)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      displayName,
      mobileNetworkCode,
      radioType,
      networkGeneration,
      cellId,
      cellSignalStrength,
    )
  }
}
@Suppress("UNCHECKED_CAST")
private object TelephonyAPICodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TelephonyInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TelephonyInfo -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TelephonyAPI {
  fun getInfo(): List<TelephonyInfo>?

  companion object {
    /** The codec used by TelephonyAPI. */
    val codec: MessageCodec<Any?> by lazy {
      TelephonyAPICodec
    }
    /** Sets up an instance of `TelephonyAPI` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: TelephonyAPI?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.TelephonyAPI.getInfo", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getInfo())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
